interface Emoji {
  emoji: string;
  name: string;
  category: string;
}
export const emojis: Emoji[] = [
  // Smileys & People
  { emoji: '😀', name: 'grinning face', category: 'smileys' },
  { emoji: '😃', name: 'grinning face with big eyes', category: 'smileys' },
  { emoji: '😄', name: 'grinning face with smiling eyes', category: 'smileys' },
  { emoji: '😁', name: 'beaming face with smiling eyes', category: 'smileys' },
  { emoji: '😆', name: 'grinning squinting face', category: 'smileys' },
  { emoji: '🥳', name: 'partying face', category: 'smileys' },
  { emoji: '😊', name: 'smiling face with smiling eyes', category: 'smileys' },
  { emoji: '😇', name: 'smiling face with halo', category: 'smileys' },
  { emoji: '🙂', name: 'slightly smiling face', category: 'smileys' },
  { emoji: '😉', name: 'winking face', category: 'smileys' },
  { emoji: '😌', name: 'relieved face', category: 'smileys' },
  { emoji: '😍', name: 'smiling face with heart-eyes', category: 'smileys' },
  { emoji: '🥰', name: 'smiling face with hearts', category: 'smileys' },
  { emoji: '😘', name: 'face blowing a kiss', category: 'smileys' },
  { emoji: '😗', name: 'kissing face', category: 'smileys' },
  { emoji: '😙', name: 'kissing face with smiling eyes', category: 'smileys' },
  { emoji: '😚', name: 'kissing face with closed eyes', category: 'smileys' },
  { emoji: '☺️', name: 'smiling face', category: 'smileys' },
  { emoji: '🤗', name: 'hugging face', category: 'smileys' },
  { emoji: '🤩', name: 'star-struck', category: 'smileys' },
  { emoji: '🤔', name: 'thinking face', category: 'smileys' },
  { emoji: '🤨', name: 'face with raised eyebrow', category: 'smileys' },
  { emoji: '😐', name: 'neutral face', category: 'smileys' },
  { emoji: '😑', name: 'expressionless face', category: 'smileys' },
  { emoji: '🙄', name: 'face with rolling eyes', category: 'smileys' },
  { emoji: '😏', name: 'smirking face', category: 'smileys' },
  { emoji: '😣', name: 'persevering face', category: 'smileys' },
  { emoji: '😥', name: 'sad but relieved face', category: 'smileys' },
  { emoji: '😮', name: 'face with open mouth', category: 'smileys' },
  { emoji: '🤐', name: 'zipper-mouth face', category: 'smileys' },
  { emoji: '😯', name: 'hushed face', category: 'smileys' },
  { emoji: '😪', name: 'sleepy face', category: 'smileys' },
  { emoji: '😫', name: 'tired face', category: 'smileys' },
  { emoji: '🥱', name: 'yawning face', category: 'smileys' },
  { emoji: '😴', name: 'sleeping face', category: 'smileys' },
  { emoji: '😷', name: 'face with medical mask', category: 'smileys' },
  { emoji: '🤒', name: 'face with thermometer', category: 'smileys' },
  { emoji: '🤕', name: 'face with head-bandage', category: 'smileys' },
  { emoji: '🤢', name: 'nauseated face', category: 'smileys' },
  { emoji: '🤮', name: 'face vomiting', category: 'smileys' },
  { emoji: '🤧', name: 'sneezing face', category: 'smileys' },
  { emoji: '🥵', name: 'hot face', category: 'smileys' },
  { emoji: '🥶', name: 'cold face', category: 'smileys' },
  { emoji: '🥴', name: 'woozy face', category: 'smileys' },
  { emoji: '😵', name: 'dizzy face', category: 'smileys' },
  { emoji: '🤯', name: 'exploding head', category: 'smileys' },
  { emoji: '😎', name: 'smiling face with sunglasses', category: 'smileys' },
  { emoji: '🤓', name: 'nerd face', category: 'smileys' },
  { emoji: '🧐', name: 'face with monocle', category: 'smileys' },

  // Animals & Nature
  { emoji: '🐶', name: 'dog face', category: 'animals' },
  { emoji: '🐱', name: 'cat face', category: 'animals' },
  { emoji: '🐭', name: 'mouse face', category: 'animals' },
  { emoji: '🐹', name: 'hamster', category: 'animals' },
  { emoji: '🐰', name: 'rabbit face', category: 'animals' },
  { emoji: '🦊', name: 'fox', category: 'animals' },
  { emoji: '🐻', name: 'bear', category: 'animals' },
  { emoji: '🐼', name: 'panda', category: 'animals' },
  { emoji: '🐨', name: 'koala', category: 'animals' },
  { emoji: '🐯', name: 'tiger face', category: 'animals' },
  { emoji: '🦁', name: 'lion', category: 'animals' },
  { emoji: '🐮', name: 'cow face', category: 'animals' },
  { emoji: '🐷', name: 'pig face', category: 'animals' },
  { emoji: '🐸', name: 'frog', category: 'animals' },
  { emoji: '🐵', name: 'monkey face', category: 'animals' },
  { emoji: '🙈', name: 'see-no-evil monkey', category: 'animals' },
  { emoji: '🙉', name: 'hear-no-evil monkey', category: 'animals' },
  { emoji: '🙊', name: 'speak-no-evil monkey', category: 'animals' },
  { emoji: '🐒', name: 'monkey', category: 'animals' },
  { emoji: '🐔', name: 'chicken', category: 'animals' },
  { emoji: '🐧', name: 'penguin', category: 'animals' },
  { emoji: '🐦', name: 'bird', category: 'animals' },
  { emoji: '🐤', name: 'baby chick', category: 'animals' },
  { emoji: '🐣', name: 'hatching chick', category: 'animals' },
  { emoji: '🐥', name: 'front-facing baby chick', category: 'animals' },
  { emoji: '🦆', name: 'duck', category: 'animals' },
  { emoji: '🦅', name: 'eagle', category: 'animals' },
  { emoji: '🦉', name: 'owl', category: 'animals' },
  { emoji: '🦇', name: 'bat', category: 'animals' },
  { emoji: '🐺', name: 'wolf', category: 'animals' },
  { emoji: '🐗', name: 'boar', category: 'animals' },
  { emoji: '🐴', name: 'horse face', category: 'animals' },
  { emoji: '🦄', name: 'unicorn', category: 'animals' },
  { emoji: '🐝', name: 'honeybee', category: 'animals' },
  { emoji: '🦋', name: 'butterfly', category: 'animals' },
  { emoji: '🐌', name: 'snail', category: 'animals' },
  { emoji: '🐞', name: 'lady beetle', category: 'animals' },
  { emoji: '🐜', name: 'ant', category: 'animals' },
  { emoji: '🦟', name: 'mosquito', category: 'animals' },
  { emoji: '🦗', name: 'cricket', category: 'animals' },
  { emoji: '🕷️', name: 'spider', category: 'animals' },
  { emoji: '🕸️', name: 'spider web', category: 'animals' },
  { emoji: '🦂', name: 'scorpion', category: 'animals' },

  // Food & Drink
  { emoji: '🍎', name: 'red apple', category: 'food' },
  { emoji: '🍊', name: 'tangerine', category: 'food' },
  { emoji: '🍋', name: 'lemon', category: 'food' },
  { emoji: '🍌', name: 'banana', category: 'food' },
  { emoji: '🍉', name: 'watermelon', category: 'food' },
  { emoji: '🍇', name: 'grapes', category: 'food' },
  { emoji: '🍓', name: 'strawberry', category: 'food' },
  { emoji: '🫐', name: 'blueberries', category: 'food' },
  { emoji: '🍈', name: 'melon', category: 'food' },
  { emoji: '🍒', name: 'cherries', category: 'food' },
  { emoji: '🍑', name: 'peach', category: 'food' },
  { emoji: '🥭', name: 'mango', category: 'food' },
  { emoji: '🍍', name: 'pineapple', category: 'food' },
  { emoji: '🥥', name: 'coconut', category: 'food' },
  { emoji: '🥝', name: 'kiwi fruit', category: 'food' },
  { emoji: '🍅', name: 'tomato', category: 'food' },
  { emoji: '🍆', name: 'eggplant', category: 'food' },
  { emoji: '🥑', name: 'avocado', category: 'food' },
  { emoji: '🥦', name: 'broccoli', category: 'food' },
  { emoji: '🥬', name: 'leafy greens', category: 'food' },
  { emoji: '🥒', name: 'cucumber', category: 'food' },
  { emoji: '🌶️', name: 'hot pepper', category: 'food' },
  { emoji: '🫑', name: 'bell pepper', category: 'food' },
  { emoji: '🌽', name: 'ear of corn', category: 'food' },
  { emoji: '🥕', name: 'carrot', category: 'food' },
  { emoji: '🧄', name: 'garlic', category: 'food' },
  { emoji: '🧅', name: 'onion', category: 'food' },
  { emoji: '🥔', name: 'potato', category: 'food' },
  { emoji: '🍠', name: 'roasted sweet potato', category: 'food' },
  { emoji: '🥐', name: 'croissant', category: 'food' },
  { emoji: '🥖', name: 'baguette bread', category: 'food' },
  { emoji: '🍞', name: 'bread', category: 'food' },
  { emoji: '🥨', name: 'pretzel', category: 'food' },
  { emoji: '🥯', name: 'bagel', category: 'food' },
  { emoji: '🥞', name: 'pancakes', category: 'food' },
  { emoji: '🧇', name: 'waffle', category: 'food' },
  { emoji: '🧀', name: 'cheese wedge', category: 'food' },
  { emoji: '🍖', name: 'meat on bone', category: 'food' },
  { emoji: '🍗', name: 'poultry leg', category: 'food' },
  { emoji: '🥩', name: 'cut of meat', category: 'food' },
  { emoji: '🥓', name: 'bacon', category: 'food' },
  { emoji: '🍔', name: 'hamburger', category: 'food' },
  { emoji: '🍟', name: 'french fries', category: 'food' },
  { emoji: '🍕', name: 'pizza', category: 'food' },
  { emoji: '🌭', name: 'hot dog', category: 'food' },
  { emoji: '🥪', name: 'sandwich', category: 'food' },
  { emoji: '🌮', name: 'taco', category: 'food' },
  { emoji: '🌯', name: 'burrito', category: 'food' },
  { emoji: '🥙', name: 'stuffed flatbread', category: 'food' },
  { emoji: '🧆', name: 'falafel', category: 'food' },
  { emoji: '🥚', name: 'egg', category: 'food' },
  { emoji: '🍳', name: 'cooking', category: 'food' },

  // Sports & Activities
  { emoji: '⚽', name: 'soccer ball', category: 'sports' },
  { emoji: '🏀', name: 'basketball', category: 'sports' },
  { emoji: '🏈', name: 'american football', category: 'sports' },
  { emoji: '⚾', name: 'baseball', category: 'sports' },
  { emoji: '🥎', name: 'softball', category: 'sports' },
  { emoji: '🎾', name: 'tennis', category: 'sports' },
  { emoji: '🏐', name: 'volleyball', category: 'sports' },
  { emoji: '🏉', name: 'rugby football', category: 'sports' },
  { emoji: '🥏', name: 'flying disc', category: 'sports' },
  { emoji: '🎱', name: 'pool 8 ball', category: 'sports' },
  { emoji: '🪀', name: 'yo-yo', category: 'sports' },
  { emoji: '🏓', name: 'ping pong', category: 'sports' },
  { emoji: '🏸', name: 'badminton', category: 'sports' },
  { emoji: '🥅', name: 'goal net', category: 'sports' },
  { emoji: '⛳', name: 'flag in hole', category: 'sports' },
  { emoji: '🪁', name: 'kite', category: 'sports' },
  { emoji: '🏹', name: 'bow and arrow', category: 'sports' },
  { emoji: '🎣', name: 'fishing pole', category: 'sports' },
  { emoji: '🤿', name: 'diving mask', category: 'sports' },
  { emoji: '🥊', name: 'boxing glove', category: 'sports' },
  { emoji: '🥋', name: 'martial arts uniform', category: 'sports' },
  { emoji: '🎽', name: 'running shirt', category: 'sports' },
  { emoji: '🛹', name: 'skateboard', category: 'sports' },
  { emoji: '🛷', name: 'sled', category: 'sports' },
  { emoji: '⛸️', name: 'ice skate', category: 'sports' },
  { emoji: '🥌', name: 'curling stone', category: 'sports' },
  { emoji: '🎿', name: 'skis', category: 'sports' },
  { emoji: '⛷️', name: 'skier', category: 'sports' },
  { emoji: '🏂', name: 'snowboarder', category: 'sports' },
  { emoji: '🪂', name: 'parachute', category: 'sports' },
  { emoji: '🏋️', name: 'person lifting weights', category: 'sports' },
  { emoji: '🤸', name: 'person cartwheeling', category: 'sports' },
  { emoji: '🤼', name: 'people wrestling', category: 'sports' },
  { emoji: '🤽', name: 'person playing water polo', category: 'sports' },
  { emoji: '🤾', name: 'person playing handball', category: 'sports' },
  { emoji: '🤹', name: 'person juggling', category: 'sports' },
  { emoji: '🧘', name: 'person in lotus position', category: 'sports' },
  { emoji: '🎪', name: 'circus tent', category: 'sports' },
  { emoji: '🎭', name: 'performing arts', category: 'sports' },
  { emoji: '🩰', name: 'ballet shoes', category: 'sports' },
  { emoji: '🎨', name: 'artist palette', category: 'sports' },
  { emoji: '🎬', name: 'clapper board', category: 'sports' },
  { emoji: '🎤', name: 'microphone', category: 'sports' },
  { emoji: '🎧', name: 'headphone', category: 'sports' },
  { emoji: '🎼', name: 'musical score', category: 'sports' },
  { emoji: '🎵', name: 'musical note', category: 'sports' },
  { emoji: '🎶', name: 'musical notes', category: 'sports' },
  { emoji: '🎹', name: 'musical keyboard', category: 'sports' },
  { emoji: '🥁', name: 'drum', category: 'sports' },
  { emoji: '🪘', name: 'long drum', category: 'sports' },
  { emoji: '🎷', name: 'saxophone', category: 'sports' },
  { emoji: '🎺', name: 'trumpet', category: 'sports' },
  { emoji: '🎸', name: 'guitar', category: 'sports' },
  { emoji: '🪕', name: 'banjo', category: 'sports' },
  { emoji: '🎻', name: 'violin', category: 'sports' },

  // Travel & Places
  { emoji: '🚗', name: 'automobile', category: 'travel' },
  { emoji: '🚕', name: 'taxi', category: 'travel' },
  { emoji: '🚙', name: 'sport utility vehicle', category: 'travel' },
  { emoji: '🚌', name: 'bus', category: 'travel' },
  { emoji: '🚎', name: 'trolleybus', category: 'travel' },
  { emoji: '🏎️', name: 'racing car', category: 'travel' },
  { emoji: '🚓', name: 'police car', category: 'travel' },
  { emoji: '🚑', name: 'ambulance', category: 'travel' },
  { emoji: '🚒', name: 'fire engine', category: 'travel' },
  { emoji: '🚐', name: 'minibus', category: 'travel' },
  { emoji: '🛻', name: 'pickup truck', category: 'travel' },
  { emoji: '🚚', name: 'delivery truck', category: 'travel' },
  { emoji: '🚛', name: 'articulated lorry', category: 'travel' },
  { emoji: '🚜', name: 'tractor', category: 'travel' },
  { emoji: '🏍️', name: 'motorcycle', category: 'travel' },
  { emoji: '🛴', name: 'kick scooter', category: 'travel' },
  { emoji: '🚲', name: 'bicycle', category: 'travel' },
  { emoji: '🛵', name: 'motor scooter', category: 'travel' },
  { emoji: '🚁', name: 'helicopter', category: 'travel' },
  { emoji: '🚟', name: 'suspension railway', category: 'travel' },
  { emoji: '🚠', name: 'mountain cableway', category: 'travel' },
  { emoji: '🚡', name: 'aerial tramway', category: 'travel' },
  { emoji: '🛶', name: 'canoe', category: 'travel' },
  { emoji: '🚤', name: 'speedboat', category: 'travel' },
  { emoji: '🛥️', name: 'motor boat', category: 'travel' },
  { emoji: '🛳️', name: 'passenger ship', category: 'travel' },
  { emoji: '⛴️', name: 'ferry', category: 'travel' },
  { emoji: '🚢', name: 'ship', category: 'travel' },
  { emoji: '✈️', name: 'airplane', category: 'travel' },
  { emoji: '🛩️', name: 'small airplane', category: 'travel' },
  { emoji: '🚁', name: 'helicopter', category: 'travel' },
  { emoji: '🪂', name: 'parachute', category: 'travel' },
  { emoji: '💺', name: 'seat', category: 'travel' },
  { emoji: '🚀', name: 'rocket', category: 'travel' },
  { emoji: '🛸', name: 'flying saucer', category: 'travel' },
  { emoji: '🚉', name: 'station', category: 'travel' },
  { emoji: '🚇', name: 'metro', category: 'travel' },
  { emoji: '🚆', name: 'train', category: 'travel' },
  { emoji: '🚄', name: 'high-speed train', category: 'travel' },
  { emoji: '🚅', name: 'bullet train', category: 'travel' },
  { emoji: '🚈', name: 'light rail', category: 'travel' },
  { emoji: '🚝', name: 'monorail', category: 'travel' },
  { emoji: '🚞', name: 'mountain railway', category: 'travel' },
  { emoji: '🚋', name: 'tram car', category: 'travel' },
  { emoji: '🚃', name: 'railway car', category: 'travel' },
  { emoji: '🚂', name: 'locomotive', category: 'travel' },

  // Objects
  { emoji: '💡', name: 'light bulb', category: 'objects' },
  { emoji: '🔦', name: 'flashlight', category: 'objects' },
  { emoji: '🕯️', name: 'candle', category: 'objects' },
  { emoji: '🪔', name: 'diya lamp', category: 'objects' },
  { emoji: '🔥', name: 'fire', category: 'objects' },
  { emoji: '💥', name: 'collision', category: 'objects' },
  { emoji: '💫', name: 'dizzy', category: 'objects' },
  { emoji: '⭐', name: 'star', category: 'objects' },
  { emoji: '🌟', name: 'glowing star', category: 'objects' },
  { emoji: '✨', name: 'sparkles', category: 'objects' },
  { emoji: '💎', name: 'gem stone', category: 'objects' },
  { emoji: '📱', name: 'mobile phone', category: 'objects' },
  { emoji: '📞', name: 'telephone receiver', category: 'objects' },
  { emoji: '☎️', name: 'telephone', category: 'objects' },
  { emoji: '📟', name: 'pager', category: 'objects' },
  { emoji: '📠', name: 'fax machine', category: 'objects' },
  { emoji: '🔋', name: 'battery', category: 'objects' },
  { emoji: '🪫', name: 'low battery', category: 'objects' },
  { emoji: '🔌', name: 'electric plug', category: 'objects' },
  { emoji: '💻', name: 'laptop', category: 'objects' },
  { emoji: '🖥️', name: 'desktop computer', category: 'objects' },
  { emoji: '🖨️', name: 'printer', category: 'objects' },
  { emoji: '⌨️', name: 'keyboard', category: 'objects' },
  { emoji: '🖱️', name: 'computer mouse', category: 'objects' },
  { emoji: '🖲️', name: 'trackball', category: 'objects' },
  { emoji: '💽', name: 'computer disk', category: 'objects' },
  { emoji: '💾', name: 'floppy disk', category: 'objects' },
  { emoji: '💿', name: 'optical disk', category: 'objects' },
  { emoji: '📀', name: 'dvd', category: 'objects' },
  { emoji: '🧮', name: 'abacus', category: 'objects' },
  { emoji: '🎥', name: 'movie camera', category: 'objects' },
  { emoji: '📹', name: 'video camera', category: 'objects' },
  { emoji: '📷', name: 'camera', category: 'objects' },
  { emoji: '📸', name: 'camera with flash', category: 'objects' },
  { emoji: '🔍', name: 'magnifying glass tilted left', category: 'objects' },
  { emoji: '🔎', name: 'magnifying glass tilted right', category: 'objects' },
  { emoji: '🕯️', name: 'candle', category: 'objects' },
  { emoji: '🪔', name: 'diya lamp', category: 'objects' },
  { emoji: '💡', name: 'light bulb', category: 'objects' },
  { emoji: '🔦', name: 'flashlight', category: 'objects' },
  { emoji: '🏮', name: 'red paper lantern', category: 'objects' },
  { emoji: '🪞', name: 'mirror', category: 'objects' },
  { emoji: '🪟', name: 'window', category: 'objects' },
  { emoji: '🛏️', name: 'bed', category: 'objects' },
  { emoji: '🛋️', name: 'couch and lamp', category: 'objects' },
  { emoji: '🪑', name: 'chair', category: 'objects' },
  { emoji: '🚽', name: 'toilet', category: 'objects' },
  { emoji: '🪠', name: 'plunger', category: 'objects' },
  { emoji: '🚿', name: 'shower', category: 'objects' },
  { emoji: '🛁', name: 'bathtub', category: 'objects' },
  { emoji: '🪤', name: 'mouse trap', category: 'objects' },
  { emoji: '🪒', name: 'razor', category: 'objects' },
  { emoji: '🧴', name: 'lotion bottle', category: 'objects' },
  { emoji: '🧷', name: 'safety pin', category: 'objects' },
  { emoji: '🧹', name: 'broom', category: 'objects' },
  { emoji: '🧺', name: 'basket', category: 'objects' },
  { emoji: '🧻', name: 'roll of paper', category: 'objects' },
  { emoji: '🪣', name: 'bucket', category: 'objects' },
  { emoji: '🧼', name: 'soap', category: 'objects' },
  { emoji: '🪥', name: 'toothbrush', category: 'objects' },
  { emoji: '🧽', name: 'sponge', category: 'objects' },
  { emoji: '🧯', name: 'fire extinguisher', category: 'objects' },
  { emoji: '🛒', name: 'shopping cart', category: 'objects' },
  { emoji: '🚬', name: 'cigarette', category: 'objects' },
  { emoji: '⚰️', name: 'coffin', category: 'objects' },
  { emoji: '🪦', name: 'headstone', category: 'objects' },
  { emoji: '⚱️', name: 'funeral urn', category: 'objects' },
  { emoji: '🗿', name: 'moai', category: 'objects' },
  { emoji: '🪧', name: 'placard', category: 'objects' },

  // Symbols
  { emoji: '❤️', name: 'red heart', category: 'symbols' },
  { emoji: '🧡', name: 'orange heart', category: 'symbols' },
  { emoji: '💛', name: 'yellow heart', category: 'symbols' },
  { emoji: '💚', name: 'green heart', category: 'symbols' },
  { emoji: '💙', name: 'blue heart', category: 'symbols' },
  { emoji: '💜', name: 'purple heart', category: 'symbols' },
  { emoji: '🖤', name: 'black heart', category: 'symbols' },
  { emoji: '🤍', name: 'white heart', category: 'symbols' },
  { emoji: '🤎', name: 'brown heart', category: 'symbols' },
  { emoji: '💔', name: 'broken heart', category: 'symbols' },
  { emoji: '❣️', name: 'heart exclamation', category: 'symbols' },
  { emoji: '💕', name: 'two hearts', category: 'symbols' },
  { emoji: '💖', name: 'sparkling heart', category: 'symbols' },
  { emoji: '💗', name: 'growing heart', category: 'symbols' },
  { emoji: '💘', name: 'heart with arrow', category: 'symbols' },
  { emoji: '💝', name: 'heart with ribbon', category: 'symbols' },
  { emoji: '💟', name: 'heart decoration', category: 'symbols' },
  { emoji: '☮️', name: 'peace symbol', category: 'symbols' },
  { emoji: '✝️', name: 'latin cross', category: 'symbols' },
  { emoji: '☪️', name: 'star and crescent', category: 'symbols' },
  { emoji: '🕉️', name: 'om', category: 'symbols' },
  { emoji: '☸️', name: 'wheel of dharma', category: 'symbols' },
  { emoji: '✡️', name: 'star of david', category: 'symbols' },
  { emoji: '🔯', name: 'dotted six-pointed star', category: 'symbols' },
  { emoji: '🕎', name: 'menorah', category: 'symbols' },
  { emoji: '☯️', name: 'yin yang', category: 'symbols' },
  { emoji: '☦️', name: 'orthodox cross', category: 'symbols' },
  { emoji: '🛐', name: 'place of worship', category: 'symbols' },
  { emoji: '⛎', name: 'ophiuchus', category: 'symbols' },
  { emoji: '♈', name: 'aries', category: 'symbols' },
  { emoji: '♉', name: 'taurus', category: 'symbols' },
  { emoji: '♊', name: 'gemini', category: 'symbols' },
  { emoji: '♋', name: 'cancer', category: 'symbols' },
  { emoji: '♌', name: 'leo', category: 'symbols' },
  { emoji: '♍', name: 'virgo', category: 'symbols' },
  { emoji: '♎', name: 'libra', category: 'symbols' },
  { emoji: '♏', name: 'scorpio', category: 'symbols' },
  { emoji: '♐', name: 'sagittarius', category: 'symbols' },
  { emoji: '♑', name: 'capricorn', category: 'symbols' },
  { emoji: '♒', name: 'aquarius', category: 'symbols' },
  { emoji: '♓', name: 'pisces', category: 'symbols' },
  { emoji: '🆔', name: 'id button', category: 'symbols' },
  { emoji: '⚡', name: 'high voltage', category: 'symbols' },
  { emoji: '🔥', name: 'fire', category: 'symbols' },
  { emoji: '💯', name: 'hundred points', category: 'symbols' },
  { emoji: '💢', name: 'anger symbol', category: 'symbols' },
  { emoji: '💨', name: 'dashing away', category: 'symbols' },
  { emoji: '💦', name: 'sweat droplets', category: 'symbols' },
  { emoji: '💤', name: 'zzz', category: 'symbols' },
  { emoji: '💥', name: 'collision', category: 'symbols' },
  { emoji: '💫', name: 'dizzy', category: 'symbols' },
  { emoji: '💬', name: 'speech balloon', category: 'symbols' },
  { emoji: '👁️‍🗨️', name: 'eye in speech bubble', category: 'symbols' },
  { emoji: '🗨️', name: 'left speech bubble', category: 'symbols' },
  { emoji: '🗯️', name: 'right anger bubble', category: 'symbols' },
  { emoji: '💭', name: 'thought balloon', category: 'symbols' },
  { emoji: '💮', name: 'white flower', category: 'symbols' },
  { emoji: '✅', name: 'check mark button', category: 'symbols' },
  { emoji: '❌', name: 'cross mark', category: 'symbols' },
  { emoji: '❎', name: 'cross mark button', category: 'symbols' },
  { emoji: '➕', name: 'plus', category: 'symbols' },
  { emoji: '➖', name: 'minus', category: 'symbols' },
  { emoji: '➗', name: 'divide', category: 'symbols' },
  { emoji: '✖️', name: 'multiply', category: 'symbols' },
  { emoji: '💲', name: 'heavy dollar sign', category: 'symbols' },
  { emoji: '💱', name: 'currency exchange', category: 'symbols' },
  { emoji: '™️', name: 'trade mark', category: 'symbols' },
  { emoji: '©️', name: 'copyright', category: 'symbols' },
  { emoji: '®️', name: 'registered', category: 'symbols' },
  { emoji: '〰️', name: 'wavy dash', category: 'symbols' },
  { emoji: '➰', name: 'curly loop', category: 'symbols' },
  { emoji: '➿', name: 'double curly loop', category: 'symbols' },
  { emoji: '🔚', name: 'end arrow', category: 'symbols' },
  { emoji: '🔙', name: 'back arrow', category: 'symbols' },
  { emoji: '🔛', name: 'on! arrow', category: 'symbols' },
  { emoji: '🔝', name: 'top arrow', category: 'symbols' },
  { emoji: '🔜', name: 'soon arrow', category: 'symbols' },
];
